### ISSUE TITLE
Example 1.4.4

### ISSUE THREAD

**Issue by discnerd** [active-calculus/prep#20]
last part of equation should have -5-\frac{1}{4}(x+7), not 5-...

Line 112 in sec-changing-linear.xml should be

f(x) = -5 -\frac{1}{4}(x - (-7)) = -5 - \frac{1}{4}(x+7)

I'd fork and edit and do a pull request, but don't really have time to do that right now, sorry.

**Comment by mattboelkins** [comment]
Thank you!  This got fixed awhile back, but I forgot to close the issue.
